name: Build and deploy JAR app to Azure Web App - java3000

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Set executable permissions
        run: chmod +x ./gradlew    

      - name: Build with Gradle
        run: ./gradlew bootJar  # Cambiado a bootJar para construir el JAR

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: './build/libs/*.jar'  # Ajusta la ruta para buscar el JAR

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Esto es necesario para solicitar el JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6671B48336C34EDAB62929B847EAE273 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_64D32A1041C94531BF071C9B09951C4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4BC44B4CA1D1492E9D51D787AE049813 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'java3000'
          slot-name: 'Production'
          package: '*.jar'

          
